# Generated by Django 5.1.6 on 2025-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('nct_id', models.CharField(max_length=11, unique=True)),
                ('official_title', models.TextField(blank=True, null=True)),
                ('brief_summary', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=50, null=True)),
                ('study_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('allocation', models.CharField(blank=True, max_length=50, null=True)),
                ('interventional_model', models.CharField(blank=True, max_length=50, null=True)),
                ('masking', models.CharField(blank=True, max_length=50, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('ipd_sharing', models.CharField(blank=True, max_length=20, null=True)),
                ('is_fda_regulated_drug', models.BooleanField(blank=True, null=True)),
                ('is_fda_regulated_device', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
                'db_table': 'studies',
            },
        ),
        migrations.CreateModel(
            name='StudyEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=20)),
                ('study_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('condition_description', models.TextField()),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_enrollment_request',
            },
        ),
    ]
