# Generated by Django 5.1.6 on 2025-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('specialty_description', models.TextField(blank=True, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('license_state', models.CharField(max_length=2)),
                ('license_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
