# Generated by Django 5.1.6 on 2025-03-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={},
        ),
        migrations.AddField(
            model_name='studies',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='sponsor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='brief_summary',
            field=models.TextField(default='No summary provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='eligibility_criteria',
            field=models.TextField(default='No Eligibility Critera Found. Check with your doctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='ipd_sharing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='is_fda_regulated_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studies',
            name='is_fda_regulated_drug',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studies',
            name='nct_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='official_title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='overall_status',
            field=models.CharField(default='Unknown Status', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='primary_purpose',
            field=models.CharField(default='Purpose Not known', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
