# Generated by Django 5.1.6 on 2025-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studies_options_studies_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='brief_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='location',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='sponsor',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
