# Generated by Django 5.1.6 on 2025-03-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adverseeventterm_pubmedarticle_searchrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='pubmed_id',
        ),
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='url',
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='article_link',
            field=models.CharField(blank=True, help_text='URL to the PubMed article', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='is_informational',
            field=models.BooleanField(default=False, help_text='Whether this is an informational article'),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='last_scanned',
            field=models.DateTimeField(auto_now=True, help_text='When this article was last scanned'),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='pmid',
            field=models.CharField(default='', help_text='PubMed ID (PMID)', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pubmedarticle',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Publication date', null=True),
        ),
        migrations.AlterField(
            model_name='pubmedarticle',
            name='title',
            field=models.TextField(blank=True, help_text='Article title', null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_search_results', to='core.pubmedarticle'),
        ),
        migrations.AlterModelTable(
            name='pubmedarticle',
            table='pubmed_articles',
        ),
    ]
