# Generated by Django 5.1.6 on 2025-03-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pubmedarticle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyenrollmentrequest',
            table='core_study_enrollment_request',
        ),
    ]
