# Generated by Django 5.1.6 on 2025-02-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('study_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nct_id', models.CharField(max_length=11, unique=True)),
                ('official_title', models.TextField()),
                ('brief_summary', models.TextField()),
                ('overall_status', models.CharField(max_length=50)),
                ('study_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'studies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.TextField()),
            ],
            options={
                'db_table': 'study_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'study_locations',
                'managed': False,
            },
        ),
    ]
