# Generated by Django 5.1.6 on 2025-02-27 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNlpInsights',
            fields=[
                ('nlp_insight_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('key_entities', models.JSONField(blank=True, null=True)),
                ('eligibility_analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_nlp_insights',
                'managed': True,
            },
        ),
    ]
