# Generated by Django 5.1.6 on 2025-02-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studynlpinsights'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClassifications',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_classifications',
            },
        ),
        migrations.CreateModel(
            name='StudyFAQs',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('faqs', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_faqs',
            },
        ),
        migrations.CreateModel(
            name='StudyRecruitmentMessages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_recruitment_messages',
            },
        ),
    ]
