# Generated by Django 5.1.6 on 2025-03-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studyreports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studynlpinsights',
            options={},
        ),
        migrations.AddField(
            model_name='studynlpinsights',
            name='simplified_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studynlpinsights',
            name='eligibility_analysis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studynlpinsights',
            name='key_entities',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studynlpinsights',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studies'),
        ),
        migrations.AlterField(
            model_name='studynlpinsights',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
