# Generated by Django 5.1.6 on 2025-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studies_options_alter_studynlpinsights_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='allocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='interventional_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='ipd_sharing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='is_fda_regulated_device',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='is_fda_regulated_drug',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='masking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='primary_purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='brief_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='official_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='overall_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studynlpinsights',
            name='eligibility_analysis',
            field=models.JSONField(),
        ),
    ]
