# Generated by Django 5.1.6 on 2025-03-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_studyclassifications_classification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclassifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studyclassifications',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studies'),
        ),
    ]
