# Generated by Django 5.1.6 on 2025-03-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_studyclassifications_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCollaborators',
            fields=[
                ('collaborator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_collaborators',
            },
        ),
        migrations.CreateModel(
            name='StudyContacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_contacts',
            },
        ),
        migrations.CreateModel(
            name='StudyDates',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_type', models.CharField(max_length=100)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_dates',
            },
        ),
        migrations.CreateModel(
            name='StudyInvestigators',
            fields=[
                ('investigator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_investigators',
            },
        ),
        migrations.CreateModel(
            name='StudyPrimaryOutcomes',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('measure', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_primary_outcomes',
            },
        ),
        migrations.CreateModel(
            name='StudySecondaryOutcomes',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('measure', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_secondary_outcomes',
            },
        ),
        migrations.CreateModel(
            name='StudySponsors',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='core.studies')),
            ],
            options={
                'db_table': 'study_sponsors',
            },
        ),
    ]
