# Generated by Django 5.1.6 on 2025-03-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=255, unique=True)),
                ('brief_title', models.CharField(max_length=500)),
                ('official_title', models.TextField(blank=True, null=True)),
                ('brief_summary', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('study_type', models.CharField(blank=True, max_length=100, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='StudyEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='api.studies')),
            ],
        ),
    ]
