# Generated by Django 5.1.6 on 2025-03-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studies_studyenrollmentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyEnrollmentRequest',
        ),
    ]
