# Generated by Django 3.2.13 on 2023-07-18 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trial_match', '0011_auto_20230701_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=50)),
                ('molecule_name', models.CharField(max_length=255)),
                ('molecule_description', models.TextField(blank=True, null=True)),
                ('molecule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('molecule_mechanism', models.TextField(blank=True, null=True)),
                ('molecule_structure', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(max_length=50)),
                ('therapeutic_area', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=255)),
                ('study_design', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('criteria', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('endpoints', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('company', models.CharField(max_length=255)),
                ('template_used', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol_outline', models.TextField(blank=True, null=True)),
                ('uncertainty_flags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('compliance_score', models.IntegerField(blank=True, null=True)),
                ('compliance_issues', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('generated_document_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('approve', 'Approve'), ('admin', 'Admin')], default='view', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='trial_match.protocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('protocol', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProtocolSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='selected', max_length=50)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('recruitment_potential', models.FloatField(blank=True, null=True)),
                ('strengths', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('weaknesses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='trial_match.protocol')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='trial_match.site')),
            ],
            options={
                'unique_together': {('protocol', 'site')},
            },
        ),
        migrations.CreateModel(
            name='ProtocolObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('exploratory', 'Exploratory')], max_length=50)),
                ('description', models.TextField()),
                ('endpoints', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timepoints', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='trial_match.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('document_snapshot', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trial_match.protocol')),
            ],
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['created_by'], name='trial_match_created_8b6341_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['company'], name='trial_match_company_c3bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['therapeutic_area'], name='trial_match_therape_9c3dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['phase'], name='trial_match_phase_7f76b2_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['status'], name='trial_match_status_7d5ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolteammember',
            index=models.Index(fields=['protocol'], name='trial_match_protoco_96e8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolteammember',
            index=models.Index(fields=['user'], name='trial_match_user_id_2b3edc_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsite',
            index=models.Index(fields=['protocol'], name='trial_match_protoco_b21fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsite',
            index=models.Index(fields=['site'], name='trial_match_site_id_e31d73_idx'),
        ),
    ] 